version: '3.1'

services: 
  frontend:
    build: .
    volumes:
      - "./frontend:/app"
    ports:
      - "3031:3000"
    depends_on: 
      - backend

  backend:
    build: .
    volumes: 
      - "./backend:/app"
    ports: 
      - "3003:3000"
    depends_on: 
      - db
    
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: teste123

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080
      
